name: "build pipeline for web release"

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
  # Runs on completion of `Daily Fetch Blades data`
  workflow_run:
    workflows: ["Daily Fetch Blades data"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm install

      - name: Codecov
        uses: codecov/codecov-action@v2.1.0

      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          service-id: srv-clhm1cug1b2c73afo7hg
          retries: 20
          wait: 16000
          sleep: 30000